version: "3"

networks:
  net:
    driver: bridge

services:
  consul:
    image: consul:1.5.1
    container_name: gokitconsul-consul
    ports:
      - 8400:8400
      - 8500:8500
      - 8600:8600
    networks:
      - net

  zipkin:
    image: openzipkin/zipkin
    container_name: gokitconsul-zipkin
    ports:
      - 9411:9411
    networks:
      - net

  authn-db:
    image: postgres:10.8-alpine
    container_name: gokitconsul-authn-db
    restart: on-failure
    environment:
      POSTGRES_DB: authn
      POSTGRES_USER: gokitconsul
      POSTGRES_PASSWORD: gokitconsul
    ports:
      - 5432:5432
    networks:
      - net

  authn:
    image: cage1016/gokitconsul-authn:latest
    container_name: gokitconsul-authn
    depends_on:
      - authn-db
    restart: on-failure
    ports:
      - 6020:6020
      - 6021:6021
    environment:
      QS_AUTHN_LOG_LEVEL: info
      QS_AUTHN_DB_HOST: authn-db
      QS_AUTHN_DB_PORT: 5432
      QS_AUTHN_DB: authn
      QS_AUTHN_DB_USER: gokitconsul
      QS_AUTHN_DB_PASS: gokitconsul
      QS_AUTHN_HTTP_PORT: 6020
      QS_AUTHN_GRPC_PORT: 6021
      QS_AUTHN_SECRET: secret
      QS_CONSULT_HOST: consul
      QS_CONSULT_PORT: 8500
      QS_ZIPKIN_V2_URL: http://zipkin:9411/api/v2/spans
    networks:
      - net

  foosvc:
    image: cage1016/gokitconsul-foosvc:latest
    container_name: gokitconsul-foosvc
    environment:
      QS_ADDSVC_LOG_LEVEL: info
      QS_FOOSVC_HTTP_PORT: 7020
      QS_FOOSVC_GRPC_PORT: 7021
      QS_CONSULT_HOST: consul
      QS_CONSULT_PORT: 8500
      QS_ADDSVC_URL: addsvc:8021
      QS_ZIPKIN_V2_URL: http://zipkin:9411/api/v2/spans
    depends_on:
      - consul
    networks:
      - net

  addsvc:
    image: cage1016/gokitconsul-addsvc:latest
    container_name: gokitconsul-addsvc
    environment:
      QS_ADDSVC_LOG_LEVEL: info
      QS_ADDSVC_HTTP_PORT: 8020
      QS_ADDSVC_GRPC_PORT: 8021
      QS_CONSULT_HOST: consul
      QS_CONSULT_PORT: 8500
      QS_ZIPKIN_V2_URL: http://zipkin:9411/api/v2/spans
    depends_on:
      - consul
    networks:
      - net

  gateway:
    image: cage1016/gokitconsul-gateway:latest
    container_name: gokitconsul-gateway
    environment:
      QS_GATEWAY_LOG_LEVEL: info
      QS_GATEWAY_HTTP_PORT: 8000
      QS_GATEWAY_GRPC_PORT: 8001
      QS_GATEWAY_SERVER_CERT: /ssl/localhost+3.pem
      QS_GATEWAY_SERVER_KEY: /ssl/localhost+3-key.pem
      QS_GATEWAY_RETRY_MAX: 3
      QS_GATEWAY_RETRY_TIMEOUT: 500
      QS_CONSULT_HOST: consul
      QS_CONSULT_PORT: 8500
      QS_ZIPKIN_V2_URL: http://zipkin:9411/api/v2/spans
    depends_on:
      - consul
    ports:
      - 8000:8000
      - 8001:8001
    volumes:
      - ./ssl:/ssl
    networks:
      - net
