// Code generated by protoc-gen-go. DO NOT EDIT.
// source: authn.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserRecord struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRecord) Reset()         { *m = UserRecord{} }
func (m *UserRecord) String() string { return proto.CompactTextString(m) }
func (*UserRecord) ProtoMessage()    {}
func (*UserRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40bfba985381dd1, []int{0}
}

func (m *UserRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRecord.Unmarshal(m, b)
}
func (m *UserRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRecord.Marshal(b, m, deterministic)
}
func (m *UserRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRecord.Merge(m, src)
}
func (m *UserRecord) XXX_Size() int {
	return xxx_messageInfo_UserRecord.Size(m)
}
func (m *UserRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRecord.DiscardUnknown(m)
}

var xxx_messageInfo_UserRecord proto.InternalMessageInfo

func (m *UserRecord) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserRecord) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginRequest struct {
	User                 *UserRecord `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40bfba985381dd1, []int{1}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUser() *UserRecord {
	if m != nil {
		return m.User
	}
	return nil
}

type LoginReply struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReply) Reset()         { *m = LoginReply{} }
func (m *LoginReply) String() string { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()    {}
func (*LoginReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40bfba985381dd1, []int{2}
}

func (m *LoginReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReply.Unmarshal(m, b)
}
func (m *LoginReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReply.Marshal(b, m, deterministic)
}
func (m *LoginReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReply.Merge(m, src)
}
func (m *LoginReply) XXX_Size() int {
	return xxx_messageInfo_LoginReply.Size(m)
}
func (m *LoginReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReply.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReply proto.InternalMessageInfo

func (m *LoginReply) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type LogoutRequest struct {
	User                 *UserRecord `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40bfba985381dd1, []int{3}
}

func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (m *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(m, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

func (m *LogoutRequest) GetUser() *UserRecord {
	if m != nil {
		return m.User
	}
	return nil
}

type LogoutReply struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutReply) Reset()         { *m = LogoutReply{} }
func (m *LogoutReply) String() string { return proto.CompactTextString(m) }
func (*LogoutReply) ProtoMessage()    {}
func (*LogoutReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40bfba985381dd1, []int{4}
}

func (m *LogoutReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutReply.Unmarshal(m, b)
}
func (m *LogoutReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutReply.Marshal(b, m, deterministic)
}
func (m *LogoutReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutReply.Merge(m, src)
}
func (m *LogoutReply) XXX_Size() int {
	return xxx_messageInfo_LogoutReply.Size(m)
}
func (m *LogoutReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutReply.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutReply proto.InternalMessageInfo

func (m *LogoutReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type AddRequest struct {
	User                 *UserRecord `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40bfba985381dd1, []int{5}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetUser() *UserRecord {
	if m != nil {
		return m.User
	}
	return nil
}

type AddReply struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddReply) Reset()         { *m = AddReply{} }
func (m *AddReply) String() string { return proto.CompactTextString(m) }
func (*AddReply) ProtoMessage()    {}
func (*AddReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40bfba985381dd1, []int{6}
}

func (m *AddReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddReply.Unmarshal(m, b)
}
func (m *AddReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddReply.Marshal(b, m, deterministic)
}
func (m *AddReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddReply.Merge(m, src)
}
func (m *AddReply) XXX_Size() int {
	return xxx_messageInfo_AddReply.Size(m)
}
func (m *AddReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AddReply.DiscardUnknown(m)
}

var xxx_messageInfo_AddReply proto.InternalMessageInfo

func (m *AddReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type BatchAddRequest struct {
	Users                []*UserRecord `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *BatchAddRequest) Reset()         { *m = BatchAddRequest{} }
func (m *BatchAddRequest) String() string { return proto.CompactTextString(m) }
func (*BatchAddRequest) ProtoMessage()    {}
func (*BatchAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40bfba985381dd1, []int{7}
}

func (m *BatchAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchAddRequest.Unmarshal(m, b)
}
func (m *BatchAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchAddRequest.Marshal(b, m, deterministic)
}
func (m *BatchAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchAddRequest.Merge(m, src)
}
func (m *BatchAddRequest) XXX_Size() int {
	return xxx_messageInfo_BatchAddRequest.Size(m)
}
func (m *BatchAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BatchAddRequest proto.InternalMessageInfo

func (m *BatchAddRequest) GetUsers() []*UserRecord {
	if m != nil {
		return m.Users
	}
	return nil
}

type BatchAddReply struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BatchAddReply) Reset()         { *m = BatchAddReply{} }
func (m *BatchAddReply) String() string { return proto.CompactTextString(m) }
func (*BatchAddReply) ProtoMessage()    {}
func (*BatchAddReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40bfba985381dd1, []int{8}
}

func (m *BatchAddReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchAddReply.Unmarshal(m, b)
}
func (m *BatchAddReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchAddReply.Marshal(b, m, deterministic)
}
func (m *BatchAddReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchAddReply.Merge(m, src)
}
func (m *BatchAddReply) XXX_Size() int {
	return xxx_messageInfo_BatchAddReply.Size(m)
}
func (m *BatchAddReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchAddReply.DiscardUnknown(m)
}

var xxx_messageInfo_BatchAddReply proto.InternalMessageInfo

func (m *BatchAddReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*UserRecord)(nil), "pb.UserRecord")
	proto.RegisterType((*LoginRequest)(nil), "pb.LoginRequest")
	proto.RegisterType((*LoginReply)(nil), "pb.LoginReply")
	proto.RegisterType((*LogoutRequest)(nil), "pb.LogoutRequest")
	proto.RegisterType((*LogoutReply)(nil), "pb.LogoutReply")
	proto.RegisterType((*AddRequest)(nil), "pb.AddRequest")
	proto.RegisterType((*AddReply)(nil), "pb.AddReply")
	proto.RegisterType((*BatchAddRequest)(nil), "pb.BatchAddRequest")
	proto.RegisterType((*BatchAddReply)(nil), "pb.BatchAddReply")
}

func init() { proto.RegisterFile("authn.proto", fileDescriptor_b40bfba985381dd1) }

var fileDescriptor_b40bfba985381dd1 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0xc6, 0xed, 0x6a, 0x47, 0x3d, 0xdd, 0xdf, 0xe8, 0x45, 0x29, 0x82, 0x33, 0x28, 0x08, 0x42,
	0x91, 0x6e, 0xe0, 0x9d, 0x50, 0xaf, 0x77, 0x55, 0xf0, 0x01, 0xda, 0x25, 0x6c, 0xc3, 0xda, 0xc4,
	0x24, 0x45, 0xf6, 0x78, 0xbe, 0x99, 0x24, 0x6d, 0xd7, 0x3a, 0x7a, 0xb3, 0xbb, 0x9e, 0xf3, 0xe5,
	0xfb, 0x7d, 0xcd, 0x39, 0x01, 0x2f, 0x2d, 0xd5, 0xae, 0x08, 0xb9, 0x60, 0x8a, 0xa1, 0x01, 0xcf,
	0xf0, 0x1b, 0xc0, 0x87, 0xa4, 0x22, 0xa1, 0x1b, 0x26, 0x08, 0xba, 0x01, 0x87, 0x7e, 0xa5, 0xfb,
	0xdc, 0xb7, 0x16, 0xd6, 0xd3, 0x55, 0x52, 0x15, 0x28, 0x00, 0x97, 0xa7, 0x52, 0xfe, 0x30, 0x41,
	0xfc, 0x81, 0x11, 0x8e, 0x35, 0x8e, 0x60, 0xb4, 0x66, 0xdb, 0x7d, 0x91, 0xd0, 0xef, 0x92, 0x4a,
	0x85, 0x30, 0x5c, 0x96, 0x92, 0x0a, 0x03, 0xf0, 0xa2, 0x49, 0xc8, 0xb3, 0xb0, 0xe5, 0x27, 0x46,
	0xc3, 0x2b, 0x80, 0xda, 0xc3, 0xf3, 0x83, 0xce, 0x54, 0xec, 0x93, 0x16, 0x4d, 0xa6, 0x29, 0xd0,
	0x0c, 0x6c, 0x2a, 0x44, 0x1d, 0xa7, 0x3f, 0xf1, 0x12, 0xc6, 0x6b, 0xb6, 0x65, 0xa5, 0x3a, 0x27,
	0xea, 0x0e, 0xbc, 0xc6, 0xa4, 0xb3, 0x6a, 0xaa, 0xd5, 0x52, 0x5f, 0x00, 0x62, 0x42, 0xce, 0x41,
	0xde, 0x82, 0x6b, 0x1c, 0xfd, 0xbc, 0x57, 0x98, 0xbe, 0xa7, 0x6a, 0xb3, 0xeb, 0x40, 0x1f, 0xc0,
	0xd1, 0x46, 0xe9, 0x5b, 0x0b, 0xbb, 0x87, 0x5a, 0x89, 0xf8, 0x1e, 0xc6, 0xad, 0xb1, 0x97, 0x1d,
	0xfd, 0x5a, 0xe0, 0xc4, 0x7a, 0x7f, 0xe8, 0x19, 0x1c, 0x33, 0x41, 0x34, 0xd3, 0xb0, 0xee, 0x02,
	0x82, 0x49, 0xa7, 0xc3, 0xf3, 0x03, 0xbe, 0x40, 0x21, 0x0c, 0xab, 0x19, 0xa0, 0x79, 0xad, 0xb5,
	0x43, 0x0c, 0xa6, 0xdd, 0x56, 0x75, 0xfe, 0x11, 0xec, 0x98, 0x10, 0x64, 0x40, 0xed, 0x35, 0x82,
	0xd1, 0xb1, 0xae, 0x8e, 0xad, 0xc0, 0x6d, 0x7e, 0x18, 0x5d, 0x6b, 0xed, 0xe4, 0xde, 0xc1, 0xfc,
	0x7f, 0xd3, 0xb8, 0xb2, 0xa1, 0x79, 0x7a, 0xcb, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x88, 0x85,
	0x6c, 0x16, 0x89, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthnClient is the client API for Authn service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthnClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutReply, error)
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddReply, error)
	BatchAdd(ctx context.Context, in *BatchAddRequest, opts ...grpc.CallOption) (*BatchAddReply, error)
}

type authnClient struct {
	cc *grpc.ClientConn
}

func NewAuthnClient(cc *grpc.ClientConn) AuthnClient {
	return &authnClient{cc}
}

func (c *authnClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := c.cc.Invoke(ctx, "/pb.Authn/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authnClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutReply, error) {
	out := new(LogoutReply)
	err := c.cc.Invoke(ctx, "/pb.Authn/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authnClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddReply, error) {
	out := new(AddReply)
	err := c.cc.Invoke(ctx, "/pb.Authn/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authnClient) BatchAdd(ctx context.Context, in *BatchAddRequest, opts ...grpc.CallOption) (*BatchAddReply, error) {
	out := new(BatchAddReply)
	err := c.cc.Invoke(ctx, "/pb.Authn/BatchAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthnServer is the server API for Authn service.
type AuthnServer interface {
	Login(context.Context, *LoginRequest) (*LoginReply, error)
	Logout(context.Context, *LogoutRequest) (*LogoutReply, error)
	Add(context.Context, *AddRequest) (*AddReply, error)
	BatchAdd(context.Context, *BatchAddRequest) (*BatchAddReply, error)
}

func RegisterAuthnServer(s *grpc.Server, srv AuthnServer) {
	s.RegisterService(&_Authn_serviceDesc, srv)
}

func _Authn_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthnServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Authn/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthnServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authn_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthnServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Authn/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthnServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authn_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthnServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Authn/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthnServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authn_BatchAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthnServer).BatchAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Authn/BatchAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthnServer).BatchAdd(ctx, req.(*BatchAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Authn_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Authn",
	HandlerType: (*AuthnServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Authn_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _Authn_Logout_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _Authn_Add_Handler,
		},
		{
			MethodName: "BatchAdd",
			Handler:    _Authn_BatchAdd_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authn.proto",
}
